web:
  restart: always
  build: ./web
  expose:
    - "8000"
  links:
    - postgres:postgres
  volumes:
    - /data/slt/static:/data/static
  env_file: .env
  command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app
  environment:
    - PYTHONUNBUFFERED=0
  log_opt:
    max-size: 50m

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - ./web/static:/www/static
    - /data/slt/static:/data/static
  volumes_from:
    - web
  links:
    - web:web
  log_opt:
    max-size: 50m

postgres:
  restart: always
  image: postgres:latest
  volumes:
    - /home/kelf/postgresdata:/var/lib/postgresql/data
  ports:
    - "5432:5432"
  environment:
    - PYTHONUNBUFFERED=0
    - POSTGRES_USER=slt-admin
    - POSTGRES_PASSWORD=Cu3nT4Cl
  log_opt:
    max-size: 50m