"""empty message

Revision ID: 2a849bd576b
Revises: 3a52c556047
Create Date: 2017-07-10 15:48:04.221746

"""

# revision identifiers, used by Alembic.
revision = '2a849bd576b'
down_revision = '3a52c556047'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
